from trie_tree.trie import Trie

if __name__ == '__main__':
    tree = Trie()
    tree.add("nivardo")
    tree.add('Nabucodonosor')
    tree.add('nação')
    tree.add("nivardox")
    tree.delete("nivardox")
    tree.add("nivardinho")
    tree.delete("nivardo")
    tree.add("karisia")
    tree.add("karisiola")
    tree.add("karisisisia")
    tree.add("karisiaaaaa")
    tree.add("karisssssia")
    tree.add("abc")
    tree.add('adc')
    tree.print()
    tree.search("nação")
    tree.search("ab")